theme: jekyll-theme-slate
title: Reilley Luedde personal project portoflio
description: Here is a compilation of some of the projects I've been working on. They mostly involve algorithms and data-science. 
twitter_username: reilley_luedde
github_username: rluedde
linkedin_username: https://www.linkedin.com/in/reilley-luedde
